// Assembles server/src/*.js into the single entry file Nakama loads (server/modules/index.js).
// The Nakama JS runtime needs ONE file with plain functions (no modules), so the sources are concatenated in a fixed order.
//   node server/build.js           write server/modules/index.js
//   node server/build.js --check   fail (exit 1) if index.js is not up to date with the sources (used in CI)
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "src");
const OUT = path.join(__dirname, "modules", "index.js");
const ORDER = ["core.js", "interlock.js", "cargo.js", "reactor.js", "match.js"];

function build() {
  const parts = ORDER.map((f) => fs.readFileSync(path.join(SRC, f), "utf8").replace(/\r\n/g, "\n").replace(/\n+$/, "\n"));
  const header = "// GENERATED by server/build.js from server/src/*.js — DO NOT EDIT THIS FILE; edit the sources and run `node server/build.js`.\n";
  return header + parts.join("\n");
}

const out = build();
if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== out) {
    console.error("server/modules/index.js is out of date: run `node server/build.js` and commit the result.");
    process.exit(1);
  }
  console.log("server/modules/index.js is up to date.");
} else {
  fs.writeFileSync(OUT, out);
  console.log("wrote " + path.relative(process.cwd(), OUT) + " (" + out.split("\n").length + " lines)");
}
