// GENERATED by server/build.js from server/src/*.js — DO NOT EDIT THIS FILE; edit the sources and run `node server/build.js`.
// Nakama authoritative match for the moving-frame spike (E1-01).
// Plain JavaScript (Nakama JS runtime, ES5 style) — no build step.
//
// Model: the boat moves deterministically as a function of time (see Assets/_Project/Scripts/Sim/BoatMotion.cs),
// so the server only simulates character positions in BOAT-LOCAL space (x = right, z = forward).
// Clients send one input per fixed input-tick (10 Hz); the server applies them in order and
// broadcasts the authoritative state each tick together with the last processed input sequence.

var MATCH_NAME = "moving_frame";
var TICK_RATE = 10;
var DT = 1 / TICK_RATE;
var OP_INPUT = 1;      // client -> server : {seq, mx, mz}
var OP_STATE = 2;      // server -> clients: {tick, t, players:[{id, x, z, seq}]}
var MOVE_SPEED = 3.0;  // m/s
var HALF_X = 3.0;      // boat interior half width (m)
var HALF_Z = 10.0;     // boat interior half length (m)
var MAX_QUEUED_INPUTS = 6;
var STATIONS = [{ x: 0, z: -9 }, { x: 0, z: 9 }]; // two-player interlock keys (boat-local), one at each end
var STATION_REACH = 2.0;       // m
var INTERLOCK_WINDOW_TICKS = 30; // 3 s at 10 Hz (GDD: Rule of Two Players)
var MAX_ALLOWANCE = 4; // max inputs a player may apply in one tick to catch up after a network stall
var MAX_PLAYERS = 4;
var REACTOR_SEED = 1234; // TODO(E3-05/run start): derive from the run so every patrol drifts differently

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

// One fixed-step integration, shared by server and (identically re-implemented) by the client prediction.
// `factor` (E2-04, default 1) scales the walking speed: what a player carries slows them down (hands.js carrySpeedFactor, mirrored in
// CharacterMotion.cs for the client's prediction).
function stepPlayer(p, mx, mz, factor) {
  var len = Math.sqrt(mx * mx + mz * mz);
  if (len > 1) { mx /= len; mz /= len; }
  var f = factor === undefined ? 1 : factor;
  p.x = clamp(p.x + mx * MOVE_SPEED * f * DT, -HALF_X, HALF_X);
  p.z = clamp(p.z + mz * MOVE_SPEED * f * DT, -HALF_Z, HALF_Z);
}

// ---- Coupled actions: the Rule of Two Players framework (E4-02) ----------------------------------------------------
// A critical action needs TWO commands, far apart, activated by two DIFFERENT players within a window of 3 s (GDD 3.4). Actions are
// DATA (COUPLED_ACTIONS); the engine below is generic: it tracks each action independently (several can be pending at once), validates
// on the server only, and calls the action's effect once per successful pair. Nothing critical may ever be executable by one player.
//
// A command is { x, z, reach, kind }. kind "press" (one key press arms the command) is the only kind for now; "hold" (cranks, pedals)
// will be added with the first action that needs it.
//
// Latency tolerance: the official window is 3 s (windowTicks, what the diegetic feedback counts down). The server accepts a second press up
// to COUPLED_GRACE_TICKS later (0.3 s) so that two players with different latency still make the window when they press in time.
var COUPLED_GRACE_TICKS = 3;

var COUPLED_ACTIONS = [
  // Spike demo pair: the two keys at the ends of the boat (kept from the E1-01 interlock).
  { id: "demo", windowTicks: INTERLOCK_WINDOW_TICKS,
    a: { x: STATIONS[0].x, z: STATIONS[0].z, reach: STATION_REACH, kind: "press" },
    b: { x: STATIONS[1].x, z: STATIONS[1].z, reach: STATION_REACH, kind: "press" } },
  // Second demo pair on the opposite diagonal: lets two pairs of players work independently at the same time.
  { id: "demo2", windowTicks: INTERLOCK_WINDOW_TICKS,
    a: { x: -2.5, z: 6.0, reach: STATION_REACH, kind: "press" },
    b: { x: 2.5, z: -7.0, reach: STATION_REACH, kind: "press" } },
  // Restart of the reactor after a SCRAM (E3-05): near the RK-1 panel and at the bow, 13 m apart.
  { id: "reactor_restart", windowTicks: INTERLOCK_WINDOW_TICKS,
    a: { x: -2.5, z: -5.0, reach: STATION_REACH, kind: "press" },
    b: { x: 2.5, z: 8.5, reach: STATION_REACH, kind: "press" } }
];

// Effects of successful actions: id -> function(state, actionId, tick). Registered by the systems that own the action (E3-05 restart...).
var COUPLED_EFFECTS = {};

function newCoupled() {
  var acts = [];
  for (var i = 0; i < COUPLED_ACTIONS.length; i++)
    acts.push({ st: [{ by: "", tick: 0 }, { by: "", tick: 0 }], result: "none", resultTick: 0, count: 0 });
  return { acts: acts };
}

// The nearest command (of any action) within its reach: { ai, side, d } or null.
function nearestCommand(pl) {
  var best = null;
  for (var i = 0; i < COUPLED_ACTIONS.length; i++) {
    for (var s = 0; s < 2; s++) {
      var c = s === 0 ? COUPLED_ACTIONS[i].a : COUPLED_ACTIONS[i].b;
      var dx = pl.x - c.x, dz = pl.z - c.z;
      var d = Math.sqrt(dx * dx + dz * dz);
      if (d <= c.reach && (best === null || d < best.d)) best = { ai: i, side: s, d: d };
    }
  }
  return best;
}

// A player presses the key at a command. Rejected when out of reach, when the command is already armed, or when the same
// player already holds the other command of that action (the rule needs two different players).
function tryActivate(cp, id, pl, tick) {
  var c = nearestCommand(pl);
  if (c === null) return;
  armCommand(cp, id, tick, c.ai, c.side);
}

// Arm command `side` of action `ai` for player `id` (shared by the nearest-command path and the aimed one, E2-02).
function armCommand(cp, id, tick, ai, side) {
  var act = cp.acts[ai];
  if (act.st[side].by !== "") return;
  if (act.st[1 - side].by === id) return;
  act.st[side].by = id; act.st[side].tick = tick;
}

// Success when both commands of an action are armed (by different players, guaranteed by tryActivate): the pair is released and the
// action's effect runs once. An armed command expires once the window plus the latency grace has passed.
function evaluateCoupled(state, tick) {
  var cp = state.cp;
  for (var i = 0; i < COUPLED_ACTIONS.length; i++) {
    var def = COUPLED_ACTIONS[i], act = cp.acts[i];
    var a = act.st[0], b = act.st[1];
    if (a.by !== "" && b.by !== "") {
      act.result = "success"; act.resultTick = tick; act.count++;
      a.by = ""; b.by = "";
      var effect = COUPLED_EFFECTS[def.id];
      if (effect) effect(state, def.id, tick);
      continue;
    }
    for (var s = 0; s < 2; s++) {
      var st = act.st[s];
      if (st.by !== "" && tick - st.tick >= def.windowTicks + COUPLED_GRACE_TICKS) {
        act.result = "timeout"; act.resultTick = tick; st.by = "";
      }
    }
  }
}

// A player left the match: release every command they had armed.
function releaseCoupled(cp, id) {
  for (var i = 0; i < cp.acts.length; i++)
    for (var s = 0; s < 2; s++) if (cp.acts[i].st[s].by === id) cp.acts[i].st[s].by = "";
}

// Broadcast (also the full resync after a reconnection). a / b = ticks left of the official window for each armed command.
function coupledView(cp, tick) {
  var out = [];
  for (var i = 0; i < COUPLED_ACTIONS.length; i++) {
    var def = COUPLED_ACTIONS[i], act = cp.acts[i];
    var rem = function (s) { return s.by === "" ? 0 : Math.max(0, def.windowTicks - (tick - s.tick)); };
    out.push({ id: def.id, a: rem(act.st[0]), b: rem(act.st[1]), ab: act.st[0].by, bb: act.st[1].by, result: act.result, rt: act.resultTick, n: act.count });
  }
  return out;
}

// ---- Carried & sliding cargo (boat-local space, no physics engine) -----------------------------------------
// Loose cargo slides on the tilted floor: the boat tilt is a deterministic function of server time (same formulas
// as BoatMotion.cs), so gravity can be projected into boat-local axes. Carried cargo follows its carrier(s).
// Light crates need one carrier; the heavy fuel flask needs two players who both grab within the 3 s window.
var GRAB_REACH = 1.5;       // m
var GRAVITY = 9.81;         // m/s^2
var FRICTION = 0.25;        // Coulomb coefficient: loose cargo starts sliding past ~14 deg of tilt
var CARGO_DEFS = [
  { id: "crate1", heavy: false, x: 2.0, z: -3.0 },
  { id: "crate2", heavy: false, x: -2.0, z: 4.0 },
  { id: "fuel", kind: "fuel", heavy: true, x: -2.0, z: -5.0 },
  // Hull patches (E6-02): the toolbox of compartment 2. Light, used up on a leak, back in the toolbox 30 s later.
  { id: "patch1", kind: "patch", heavy: false, x: 0.6, z: 5.5 },
  { id: "patch2", kind: "patch", heavy: false, x: 1.0, z: 5.5 },
  { id: "patch3", kind: "patch", heavy: false, x: 1.4, z: 5.5 },
  // Bucket (E6-03): same toolbox, never used up.
  { id: "bucket", kind: "bucket", heavy: false, x: 1.8, z: 5.5 },
  // Torch (E2-03): the restart "à la lampe torche" (GDD 3.3); one hand, or the chest pocket.
  { id: "flashlight", kind: "flashlight", heavy: false, x: 0.2, z: 5.5 }
];
// Boat tilt (must match BoatMotion.cs defaults: pitch 15 deg / 7 s, roll 20 deg / 5 s + 1 rad phase).
var PITCH_AMP = 15 * Math.PI / 180, PITCH_PERIOD = 7;
var ROLL_AMP = 20 * Math.PI / 180, ROLL_PERIOD = 5;

// Horizontal part of the world "up" vector expressed in boat-local axes: up_local = (cos p sin r, cos p cos r, -sin p).
// trimDeg / listDeg (E6-01) are the offsets the water's weight adds to the scripted swell (same as BoatMotion.Evaluate with offsets).
function boatUpHorizontal(t, trimDeg, listDeg) {
  var tau = 2 * Math.PI;
  var p = PITCH_AMP * Math.sin(tau * t / PITCH_PERIOD) + (trimDeg || 0) * Math.PI / 180;
  var r = ROLL_AMP * Math.sin(tau * t / ROLL_PERIOD + 1.0) + (listDeg || 0) * Math.PI / 180;
  return { x: Math.cos(p) * Math.sin(r), z: -Math.sin(p) };
}

function newCargo() {
  var out = [];
  for (var i = 0; i < CARGO_DEFS.length; i++) {
    var d = CARGO_DEFS[i];
    out.push({ id: d.id, kind: d.kind || "crate", heavy: d.heavy, x: d.x, z: d.z, vx: 0, vz: 0, carriers: [], pend: "", pendTick: 0,
               active: true, respawnTick: 0, homeX: d.x, homeZ: d.z, y: 0, vy: 0, fly: false });
  }
  return out;
}

// A thrown item (E2-04): ballistic in the boat's frame (gravity only, no boat inertia), bounces on the walls, lands on the floor and then
// slides like any loose cargo. Deterministic: plain arithmetic on the tick.
function flyStep(c) {
  c.x += c.vx * DT; c.z += c.vz * DT;
  c.vy -= GRAVITY * DT;
  c.y += c.vy * DT;
  if (c.x < -HALF_X || c.x > HALF_X) { c.x = clamp(c.x, -HALF_X, HALF_X); c.vx = -c.vx * THROW_BOUNCE; }
  if (c.z < -HALF_Z || c.z > HALF_Z) { c.z = clamp(c.z, -HALF_Z, HALF_Z); c.vz = -c.vz * THROW_BOUNCE; }
  if (c.y <= 0) { c.y = 0; c.vy = 0; c.fly = false; c.vx *= THROW_LAND_KEEP; c.vz *= THROW_LAND_KEEP; }
}

function slideStep(c, up) {
  var ax = -GRAVITY * up.x, az = -GRAVITY * up.z, amag = Math.sqrt(ax * ax + az * az);
  var vmag = Math.sqrt(c.vx * c.vx + c.vz * c.vz);
  var dirx, dirz;
  if (vmag < 1e-6) {
    if (amag <= FRICTION * GRAVITY) { c.vx = 0; c.vz = 0; return; } // static friction holds it
    dirx = ax / amag; dirz = az / amag;
  } else { dirx = c.vx / vmag; dirz = c.vz / vmag; }
  var nvx = c.vx + (ax - FRICTION * GRAVITY * dirx) * DT;
  var nvz = c.vz + (az - FRICTION * GRAVITY * dirz) * DT;
  if (vmag >= 1e-6 && (nvx * c.vx + nvz * c.vz) <= 0) { nvx = 0; nvz = 0; } // friction stopped it
  c.vx = nvx; c.vz = nvz;
  c.x += c.vx * DT; c.z += c.vz * DT;
  if (c.x < -HALF_X || c.x > HALF_X) { c.x = clamp(c.x, -HALF_X, HALF_X); c.vx = 0; }
  if (c.z < -HALF_Z || c.z > HALF_Z) { c.z = clamp(c.z, -HALF_Z, HALF_Z); c.vz = 0; }
}

function updateCargo(state, tick) {
  var tilt = waterTilt(state.water);
  var up = boatUpHorizontal(tick * DT, tilt.trim, tilt.list);
  for (var i = 0; i < state.cargo.length; i++) {
    var c = state.cargo[i];
    if (!c.active) {                                               // used patch: back in the toolbox after PATCH_RESPAWN_TICKS
      if (tick >= c.respawnTick) { c.active = true; c.x = c.homeX; c.z = c.homeZ; c.vx = 0; c.vz = 0; }
      continue;
    }
    if (c.fly) { flyStep(c); continue; }                          // thrown: in the air until it lands
    if (c.pend !== "" && tick - c.pendTick >= INTERLOCK_WINDOW_TICKS) c.pend = ""; // second carrier too late
    // A carrier that left the match releases the cargo
    var alive = [];
    for (var k = 0; k < c.carriers.length; k++) if (state.players[c.carriers[k]]) alive.push(c.carriers[k]);
    if (alive.length !== c.carriers.length) { c.carriers = []; c.vx = 0; c.vz = 0; }
    if (c.pend !== "" && !state.players[c.pend]) c.pend = "";
    if (c.carriers.length === 1) {
      var p1 = state.players[c.carriers[0]]; c.x = p1.x; c.z = p1.z; c.vx = 0; c.vz = 0;
    } else if (c.carriers.length === 2) {
      var pa = state.players[c.carriers[0]], pb = state.players[c.carriers[1]];
      c.x = (pa.x + pb.x) / 2; c.z = (pa.z + pb.z) / 2; c.vx = 0; c.vz = 0;
    } else {
      slideStep(c, up);
    }
  }
}

function cargoView(cargo) {
  var out = [];
  for (var i = 0; i < cargo.length; i++) {
    var c = cargo[i];
    out.push({ id: c.id, x: c.x, z: c.z, h: c.heavy ? 1 : 0, c: c.carriers, p: c.pend, k: c.kind, a: c.active ? 1 : 0, y: Math.round(c.y * 100) / 100 });
  }
  return out;
}

// ---- Hands: one hand = one thing (E2-03) ------------------------------------------------------------------------------------------
// GDD 5: "une main = une chose". A player has a left hand, a right hand and ONE chest pocket (a single small item: a torch, a stamp, a sandwich),
// no inventory beyond that. Items are described in data (ITEM_KINDS): how many hands they need and whether they fit the pocket. A two-handed
// item (a crate, the fuel flask, later the 8 kg Manual) takes both hands and LOCKS every other action: pressing a control, holding a valve
// wheel or arming a command of the Rule of Two Players all need a free hand (canUseHands). Using the item you hold (a patch on a leak, the
// bucket in the water) needs no extra hand. The heavy flask is carried by two players, each with both hands.
//
// Protocol (input fields): take (pick the nearest item into free hands), drop (true = the last item taken, or "L" / "R" / "P" for a slot), stow
// (a pocketable one-hand item goes hand -> pocket, or pocket -> hand). The legacy field grab stays: it drops what you hold, else takes (the old F key).
// mass in kg (E2-04): what you carry slows you down, a shared (heavy) item is carried half each.
var ITEM_KINDS = {
  crate: { hands: 2, mass: 12 },
  fuel: { hands: 2, mass: 40 },
  patch: { hands: 1, mass: 1 },
  bucket: { hands: 1, mass: 2 },
  flashlight: { hands: 1, pocket: true, mass: 0.5 }
};
var CARRY_SLOWDOWN_PER_KG = 0.012;       // walking speed factor = 1 - this x carried mass ...
var CARRY_MIN_FACTOR = 0.5;              // ... never below this
var THROW_SPEED = 6;                     // m/s horizontal, along the player's heading (E2-04)
var THROW_UP = 2;                        // m/s upwards: a small arc
var THROW_HEIGHT = 1.2;                  // m above the floor when it leaves the hand
var THROW_BOUNCE = 0.3;                  // fraction of the speed kept after hitting a wall
var THROW_LAND_KEEP = 0.5;               // fraction of the horizontal speed kept on landing: the item then slides like any loose cargo

function newHands() { return { l: "", r: "", p: "", order: [] }; }     // slots hold cargo ids; order = items in the order they were taken

function itemKind(item) { return ITEM_KINDS[item.kind] || ITEM_KINDS.crate; }
function cargoById(cargo, id) {
  for (var i = 0; i < cargo.length; i++) if (cargo[i].id === id) return cargo[i];
  return null;
}
function freeHandCount(h) { return (h.l === "" ? 1 : 0) + (h.r === "" ? 1 : 0); }
function holdsTwoHanded(h) { return h.l !== "" && h.l === h.r; }
function holdsAnything(h) { return h.l !== "" || h.r !== "" || h.p !== ""; }
// Mass carried by a player (kg): every distinct item in their hands and pocket, a heavy item counts half (two carriers).
function carriedMass(state, playerId) {
  var h = state.players[playerId].hands, seen = [], mass = 0;
  var slots = [h.l, h.r, h.p];
  for (var i = 0; i < slots.length; i++) {
    if (slots[i] === "" || seen.indexOf(slots[i]) >= 0) continue;
    seen.push(slots[i]);
    var item = cargoById(state.cargo, slots[i]);
    if (item) mass += itemKind(item).mass / (item.heavy ? 2 : 1);
  }
  return mass;
}
// Walking speed factor from the mass carried (1 = empty hands).
function carrySpeedFactor(state, playerId) {
  return Math.max(CARRY_MIN_FACTOR, 1 - CARRY_SLOWDOWN_PER_KG * carriedMass(state, playerId));
}

// A control may be pressed (or a valve held, or a command armed) only with a free hand and no two-handed item.
function canUseHands(pl) { return !holdsTwoHanded(pl.hands) && freeHandCount(pl.hands) >= 1; }

// The item of a given kind held in a HAND (not the pocket) by the player, or null (bucket, patch...).
function handItem(state, playerId, kind) {
  var h = state.players[playerId].hands;
  var slots = [h.r, h.l];
  for (var i = 0; i < slots.length; i++) {
    if (slots[i] === "") continue;
    var item = cargoById(state.cargo, slots[i]);
    if (item && item.kind === kind && item.carriers.indexOf(playerId) >= 0) return item;
  }
  return null;
}

function removeFromHands(h, itemId) {
  if (h.l === itemId) h.l = "";
  if (h.r === itemId) h.r = "";
  if (h.p === itemId) h.p = "";
  var k = h.order.indexOf(itemId);
  if (k >= 0) h.order.splice(k, 1);
}

// Pick the nearest free item within reach into free hands. A heavy item needs a second player taking it within the window (cargo.js: pend).
function takeItem(state, id, pl, tick) {
  var h = pl.hands, best = null, bestD = GRAB_REACH;
  for (var i = 0; i < state.cargo.length; i++) {
    var c = state.cargo[i];
    if (!c.active) continue;                                        // a used patch is not in the world until it respawns
    if (c.carriers.length >= (c.heavy ? 2 : 1)) continue;
    if (c.carriers.indexOf(id) >= 0 || c.pend === id) continue;
    if (c.fly) continue;                                            // an item in the air cannot be caught
    var dx = pl.x - c.x, dz = pl.z - c.z, d = Math.sqrt(dx * dx + dz * dz);
    if (d <= bestD) { best = c; bestD = d; }
  }
  if (!best) return false;
  var need = itemKind(best).hands;
  if (freeHandCount(h) < need) return false;
  if (best.heavy) {
    if (best.pend === "") { best.pend = id; best.pendTick = tick; }
    else { best.carriers = [best.pend, id]; best.pend = ""; }
  } else best.carriers = [id];
  if (need === 2) { h.l = best.id; h.r = best.id; } else if (h.r === "") h.r = best.id; else h.l = best.id;
  h.order.push(best.id);
  return true;
}

// Let go of an item: it stays where the player stands. which: true / "" = the last item taken, "L" / "R" / "P" = a slot. Dropping a shared
// (heavy) carry makes both carriers let go.
function dropItem(state, id, pl, which) {
  var h = pl.hands, itemId = "";
  if (which === "L") itemId = h.l; else if (which === "R") itemId = h.r; else if (which === "P") itemId = h.p;
  else if (h.order.length > 0) itemId = h.order[h.order.length - 1];
  if (itemId === "") return false;
  releaseItem(state, itemId);
  return true;
}

// The item leaves everybody's hands and carriers (a dropped flask drops for both of its carriers).
function releaseItem(state, itemId) {
  var item = cargoById(state.cargo, itemId);
  if (item) { item.carriers = []; item.pend = ""; item.vx = 0; item.vz = 0; }
  for (var k = 0; k < state.order.length; k++) removeFromHands(state.players[state.order[k]].hands, itemId);
}

// Throw the last one-hand item taken (from a hand, not the pocket) along the player's heading: a small arc in the boat's frame, a bounce on
// the walls, then it lands and slides (cargo.js flyStep). Two-handed items, the pocket and empty hands throw nothing.
function throwItem(state, id, pl) {
  var h = pl.hands;
  for (var i = h.order.length - 1; i >= 0; i--) {
    var item = cargoById(state.cargo, h.order[i]);
    if (!item || itemKind(item).hands !== 1) continue;
    if (h.l !== item.id && h.r !== item.id) continue;               // in the pocket: not thrown
    releaseItem(state, item.id);
    item.x = pl.x; item.z = pl.z;
    item.vx = THROW_SPEED * Math.sin(pl.yaw); item.vz = THROW_SPEED * Math.cos(pl.yaw);
    item.y = THROW_HEIGHT; item.vy = THROW_UP; item.fly = true;
    return true;
  }
  return false;
}

// hand <-> pocket for a pocketable one-hand item: the pocket holds ONE small thing.
function stowItem(state, id, pl) {
  var h = pl.hands;
  if (h.p !== "") {                                                 // pocket -> a free hand
    if (freeHandCount(h) < 1) return false;
    var out = h.p;
    h.p = "";
    if (h.r === "") h.r = out; else h.l = out;
    return true;
  }
  for (var i = h.order.length - 1; i >= 0; i--) {                   // hand -> pocket: the last pocketable one-hand item taken
    var item = cargoById(state.cargo, h.order[i]);
    if (!item || !itemKind(item).pocket || itemKind(item).hands !== 1) continue;
    if (h.l === item.id) h.l = ""; else if (h.r === item.id) h.r = ""; else continue;
    h.p = item.id;
    return true;
  }
  return false;
}

// The legacy F key: let go of what you hold, otherwise pick up the nearest item.
function grabToggle(state, id, pl, tick) {
  if (holdsAnything(pl.hands)) dropItem(state, id, pl, true);
  else takeItem(state, id, pl, tick);
}

// A player left the match: everything they held is let go.
function releasePlayerItems(state, id) {
  var pl = state.players[id];
  if (!pl) return;
  var ids = [pl.hands.l, pl.hands.r, pl.hands.p];
  for (var i = 0; i < ids.length; i++) if (ids[i] !== "") releaseItem(state, ids[i]);
  for (var c = 0; c < state.cargo.length; c++) if (state.cargo[c].pend === id) state.cargo[c].pend = "";
}

// Keep the slots truthful: an item that is no longer carried by that player (the second carrier did not come in time, a used patch, a carrier who
// left) leaves their hands.
function syncHands(state) {
  for (var k = 0; k < state.order.length; k++) {
    var pid = state.order[k], h = state.players[pid].hands;
    var slots = ["l", "r", "p"];
    for (var s = 0; s < slots.length; s++) {
      var itemId = h[slots[s]];
      if (itemId === "") continue;
      var item = cargoById(state.cargo, itemId);
      var valid = item && item.active && (item.carriers.indexOf(pid) >= 0 || item.pend === pid);
      if (!valid) removeFromHands(h, itemId);
    }
  }
}

// Broadcast (and resync): what a player holds, [left, right, pocket] as cargo ids ("" = empty).
function handsView(h) { return [h.l, h.r, h.p]; }

// ---- Water by volume per compartment and the boat's trim / list (E6-01) -----------------------------------------------------
// GDD 8: water is simulated as a VOLUME per compartment plus a centre of mass (no fluid). Six compartments in a line from the bow (+z)
// to the stern (-z) over the 20 m of the spike. Water never appears or disappears except through the explicit API (waterAdd for
// leaks, waterRemove for bilge pumps: E6-02 / E6-03); it flows between neighbouring compartments through OPEN bulkhead openings in
// proportion to the level difference. Its weight shifts the centre of mass, which adds a trim (pitch) and a list (roll) to the scripted
// swell of the boat (BoatMotion). Deterministic: pure arithmetic on the tick, no randomness.
var WATER_COMPARTMENTS = [
  { id: "torpilles", z0: 20 / 3, z1: 10, volume: 40 },            // 1 bow
  { id: "central", z0: 10 / 3, z1: 20 / 3, volume: 40 },          // 2
  { id: "radio", z0: 0, z1: 10 / 3, volume: 40 },                 // 3
  { id: "reacteur", z0: -10 / 3, z1: 0, volume: 40 },             // 4
  { id: "machines", z0: -20 / 3, z1: -10 / 3, volume: 40 },       // 5
  { id: "vie", z0: -10, z1: -20 / 3, volume: 40 }                 // 6 stern
];
var WATER_HEIGHT = 2.0;            // m: a full compartment is 2 m deep, so level = volume / (capacity / 2)
var WATER_FLOW = 2.0;              // m3/s per metre of level difference through an open bulkhead opening (time constant ~5 s)
var WATER_DENSITY = 1000;          // kg/m3
var TRIM_PER_TM = 0.036;           // degrees of pitch per tonne-metre of longitudinal moment (40 m3 at the bow ~ 12 deg)
var LIST_PER_TM = 0.2;             // degrees of roll per tonne-metre of lateral moment
var MAX_TRIM_DEG = 12, MAX_LIST_DEG = 15;
var HALF_BEAM = 1.5;               // m: lateral position of water that stands against a side

function newWater() {
  var comps = [], doors = [];
  for (var i = 0; i < WATER_COMPARTMENTS.length; i++) comps.push({ w: 0, side: 0 });   // w = m3, side = -1 (left) .. +1 (right) bias of the water
  for (var d = 0; d < WATER_COMPARTMENTS.length - 1; d++) doors.push({ open: true });      // door d joins compartment d and d+1
  return { comps: comps, doors: doors, rejected: 0 };
}

function waterLevel(w, i) { return w.comps[i].w / (WATER_COMPARTMENTS[i].volume / WATER_HEIGHT); }   // m

// Which compartment contains boat-local z (clamped to the ends).
function compartmentAt(z) {
  for (var i = 0; i < WATER_COMPARTMENTS.length; i++) if (z >= WATER_COMPARTMENTS[i].z0 && z < WATER_COMPARTMENTS[i].z1) return i;
  return z < 0 ? WATER_COMPARTMENTS.length - 1 : 0;
}

// Pour `volume` m3 into compartment i (a leak). `side` (-1 left, 0 centre, +1 right) is where it stands. Returns the volume accepted:
// what does not fit in a full compartment is counted in water.rejected (the boat is flooded there).
function waterAdd(w, i, volume, side) {
  var c = w.comps[i], cap = WATER_COMPARTMENTS[i].volume;
  var ok = Math.max(0, Math.min(volume, cap - c.w));
  var tot = c.w + ok;
  if (tot > 0) c.side = (c.side * c.w + (side || 0) * ok) / tot;
  c.w = tot;
  w.rejected += volume - ok;
  return ok;
}

// Take up to `volume` m3 out of compartment i (a bilge pump). Returns the volume removed.
function waterRemove(w, i, volume) {
  var c = w.comps[i];
  var ok = Math.max(0, Math.min(volume, c.w));
  c.w -= ok;
  if (c.w < 1e-12) { c.w = 0; c.side = 0; }
  return ok;
}

function waterSetDoor(w, d, open) {
  if (d < 0 || d >= w.doors.length) return false;
  w.doors[d].open = !!open;
  return true;
}

function waterTotal(w) {
  var t = 0;
  for (var i = 0; i < w.comps.length; i++) t += w.comps[i].w;
  return t;
}

// One 10 Hz step: flow through open openings (computed from the levels at the start of the step, applied in order, never more than the
// source holds nor than the destination can take), so the total is conserved to the last bit of rounding.
function waterStep(w) {
  var n = w.doors.length, q = new Array(n);
  for (var d = 0; d < n; d++) q[d] = w.doors[d].open ? WATER_FLOW * (waterLevel(w, d) - waterLevel(w, d + 1)) * DT : 0;
  for (var k = 0; k < n; k++) {
    var from = q[k] >= 0 ? k : k + 1, to = q[k] >= 0 ? k + 1 : k, vol = Math.abs(q[k]);
    vol = Math.min(vol, w.comps[from].w, WATER_COMPARTMENTS[to].volume - w.comps[to].w);
    if (vol <= 0) continue;
    // moved water arrives centred: it dilutes the lateral bias of the destination
    var dest = w.comps[to], tot = dest.w + vol;
    dest.side = (dest.side * dest.w) / tot;
    dest.w = tot;
    w.comps[from].w -= vol;
    if (w.comps[from].w < 1e-12) { w.comps[from].w = 0; w.comps[from].side = 0; }
  }
}

function clampDeg(v, lim) { return v < -lim ? -lim : (v > lim ? lim : v); }

// Centre-of-mass effect: trim (pitch, + = bow down) from the longitudinal moment, list (roll) from the lateral one. Degrees.
function waterTilt(w) {
  var mz = 0, mx = 0;                                              // tonne-metres
  for (var i = 0; i < w.comps.length; i++) {
    var c = w.comps[i], mass = c.w * WATER_DENSITY / 1000;         // tonnes
    var zc = (WATER_COMPARTMENTS[i].z0 + WATER_COMPARTMENTS[i].z1) / 2;
    var fill = c.w / WATER_COMPARTMENTS[i].volume;
    mz += mass * zc;
    mx += mass * c.side * HALF_BEAM * (1 - fill);                  // standing against a side, it spreads to the middle as the compartment fills
  }
  return { trim: clampDeg(TRIM_PER_TM * mz, MAX_TRIM_DEG) || 0, list: clampDeg(-LIST_PER_TM * mx, MAX_LIST_DEG) || 0 };   // || 0: never -0
}

// Broadcast (and resync): l = fill fraction 0..1 per compartment, m = total mass in tonnes, tr / li = trim and list offsets (deg),
// dr = bulkhead openings (1 open), ov = volume rejected by full compartments.
function waterView(w) {
  function q(x, k) { return Math.round(x * k) / k; }
  var l = [], dr = [], t = waterTilt(w);
  for (var i = 0; i < w.comps.length; i++) l.push(q(w.comps[i].w / WATER_COMPARTMENTS[i].volume, 1000));
  for (var d = 0; d < w.doors.length; d++) dr.push(w.doors[d].open ? 1 : 0);
  return { l: l, m: q(waterTotal(w) * WATER_DENSITY / 1000, 10), tr: q(t.trim, 100), li: q(t.list, 100), dr: dr, ov: q(w.rejected, 100) };
}

// ---- Hull leaks and their repair (E6-02) -------------------------------------------------------------------------------------
// A leak is a hole in the hull (left or right wall of a compartment) that pours water into that compartment at the flow rate of its size
// (waterAdd every tick, so the boat lists towards the leak's side) until it is repaired. PROTO: ONE leak at a time, scheduled by a seeded
// event (first at ~90 s, the next one 60-120 s after the previous is sealed); other systems (E3-09 failure generator, E7 damage) create
// leaks through leakCreate. Repair v0: carry a "hull patch" (a light cargo item, taken from the toolbox of compartment 2) to the leak and press
// the interaction key; each patch lowers the leak one size (large -> medium -> small -> sealed) and is used up. The hammer / wrench / wedge
// of the full repair kit wait for the one-hand inventory (E2-03/E2-04): the leak "type" is already there to hook them up.
var LEAK_RATES = [0, 0.02, 0.08, 0.25];      // m3/s per size: 0 sealed, 1 small, 2 medium, 3 large
var LEAK_REACH = 1.5;                        // m: a patch must be applied within this distance of the hole
var LEAK_SEED = 5678;
var LEAK_FIRST_TICK = 900;                   // first leak at 90 s
var LEAK_GAP_MIN_TICKS = 600, LEAK_GAP_SPAN_TICKS = 600;   // next one 60-120 s after the previous is sealed
var PATCH_RESPAWN_TICKS = 300;               // a used patch is back in the toolbox after 30 s

function newLeaks() { return { list: [], nextId: 1, rng: LEAK_SEED | 0, nextTick: LEAK_FIRST_TICK }; }

// Seeded PRNG (mulberry32, same family as the reactor's): the state is one uint32 in the leaks object.
function leakRand(L) {
  L.rng = (L.rng + 0x6D2B79F5) | 0;
  var t = Math.imul(L.rng ^ (L.rng >>> 15), 1 | L.rng);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}

// Open a leak on the hull wall of a compartment. side -1 = left wall, +1 = right wall, z = position along the boat. size 1..3.
function leakCreate(L, z, side, size) {
  var s = side < 0 ? -1 : 1, sz = Math.max(1, Math.min(3, size | 0));
  var leak = { id: L.nextId++, comp: compartmentAt(z), x: s * HALF_X, z: z, side: s, size: sz, type: sz === 1 ? "rivet" : "plate" };
  L.list.push(leak);
  return leak;
}

function leakRate(leak) { return LEAK_RATES[leak.size]; }

// Nearest leak within reach of a player, or null.
function nearestLeak(L, pl) {
  var best = null, bestD = LEAK_REACH;
  for (var i = 0; i < L.list.length; i++) {
    var dx = pl.x - L.list[i].x, dz = pl.z - L.list[i].z, d = Math.sqrt(dx * dx + dz * dz);
    if (d <= bestD) { best = L.list[i]; bestD = d; }
  }
  return best;
}

// The interaction key was pressed: a player carrying a patch next to a leak applies it. Returns true when the press was a repair.
// `aimed` (E2-02): the leak the player is looking at; it must exist and be within reach. Without it the nearest leak in reach is used.
function tryRepair(state, id, pl, tick, aimed) {
  var held = handItem(state, id, "patch");
  if (!held) return false;
  var leak = aimed || nearestLeak(state.leaks, pl);
  if (!leak) return false;
  if (aimed) {
    var dx = pl.x - aimed.x, dz = pl.z - aimed.z;
    if (Math.sqrt(dx * dx + dz * dz) > LEAK_REACH) return false;
  }
  leak.size--;
  held.active = false; held.carriers = []; held.vx = 0; held.vz = 0; held.respawnTick = tick + PATCH_RESPAWN_TICKS;
  if (leak.size <= 0) {
    state.leaks.list.splice(state.leaks.list.indexOf(leak), 1);
    state.leaks.nextTick = tick + LEAK_GAP_MIN_TICKS + Math.floor(leakRand(state.leaks) * LEAK_GAP_SPAN_TICKS);
  }
  return true;
}

// One 10 Hz step: the scheduled event may open a leak (only when none is active), every open leak pours water.
function leakStep(state, tick) {
  var L = state.leaks;
  if (L.list.length === 0 && tick >= L.nextTick) {
    var c = Math.min(WATER_COMPARTMENTS.length - 1, Math.floor(leakRand(L) * WATER_COMPARTMENTS.length));
    var comp = WATER_COMPARTMENTS[c];
    var z = comp.z0 + 0.5 + leakRand(L) * (comp.z1 - comp.z0 - 1);
    var side = leakRand(L) < 0.5 ? -1 : 1;
    var r = leakRand(L), size = r < 0.5 ? 1 : (r < 0.85 ? 2 : 3);
    leakCreate(L, z, side, size);
  }
  for (var i = 0; i < L.list.length; i++) waterAdd(state.water, L.list[i].comp, leakRate(L.list[i]) * DT, L.list[i].side);
}

// Broadcast (and resync): every open leak.
function leaksView(L) {
  var out = [];
  for (var i = 0; i < L.list.length; i++) {
    var k = L.list[i];
    out.push({ id: k.id, c: k.comp, x: k.x, z: Math.round(k.z * 100) / 100, s: k.size, t: k.type });
  }
  return out;
}

// ---- Bilge pumps and the bucket (E6-03) -------------------------------------------------------------------------------------
// Two electric bilge pumps each pump the water out of THEIR OWN compartment at BILGE_CAPACITY (water in neighbouring compartments reaches it
// through the open bulkhead openings, E6-01). A pump runs only while it is switched on, not broken, its breaker is closed and the bus voltage
// is high enough (power.js, E3-07): a SCRAM drops the voltage to zero and stops them, and the boat is bailed by hand. Bucket: a light cargo item (the toolbox of compartment 2); carried into a flooded compartment, one press
// scoops BUCKET_VOLUME out, at most once per BUCKET_COOLDOWN_TICKS per player. The mop waits for the spills of E6-05.
var BILGE_PUMPS = [
  { id: "bilge0", comp: 1, x: -2.5, z: 4.5, reach: 1.0 },     // compartment 2, left wall
  { id: "bilge1", comp: 4, x: 2.5, z: -5.0, reach: 0.9 }      // compartment 5, right wall
];
var BILGE_CAPACITY = 0.15;         // m3/s per pump
var BUCKET_VOLUME = 0.015;         // m3 (15 L) per scoop
var BUCKET_COOLDOWN_TICKS = 15;    // 1.5 s per player between two scoops

function newBilge() {
  var pumps = [];
  for (var i = 0; i < BILGE_PUMPS.length; i++) pumps.push({ on: false, broken: false, run: false });
  return { pumps: pumps, scoopTick: {} };           // scoopTick: player id -> tick of their last scoop
}

// A press at the pump's switch: toggles run/stop. A broken pump cannot be started.
function bilgeToggle(b, i) {
  var p = b.pumps[i];
  if (!p.on && p.broken) return false;
  p.on = !p.on;
  return true;
}

// Breakdown / repair (nothing triggers a breakdown yet: E3-09; the spare part is E5/E9). A repaired pump stays stopped.
function bilgeBreak(b, i) { b.pumps[i].broken = true; b.pumps[i].on = false; b.pumps[i].run = false; return true; }
function bilgeRepair(b, i) { b.pumps[i].broken = false; return true; }

// A bilge pump is fed when its breaker (use "bilge", pump i) is closed and the bus voltage is at least BILGE_MIN_V.
function pumpPowered(state, i) {
  for (var b = 0; b < BREAKERS.length; b++) if (BREAKERS[b].use === "bilge" && BREAKERS[b].pump === i) return consumerPowered(state.power, b, BILGE_MIN_V);
  return false;
}

// One 10 Hz step: every running pump takes up to BILGE_CAPACITY * DT out of its compartment.
function bilgeStep(state) {
  for (var i = 0; i < BILGE_PUMPS.length; i++) {
    var p = state.bilge.pumps[i];
    p.run = false;
    if (!p.on || p.broken || !pumpPowered(state, i)) continue;
    p.run = waterRemove(state.water, BILGE_PUMPS[i].comp, BILGE_CAPACITY * DT) > 0;
  }
}

// The interaction key pressed by a player carrying the bucket: scoop water out of the compartment they stand in. Returns true when the press
// was used by the bucket (a scoop, or a scoop refused by the cooldown); false lets the press go to whatever else is in reach.
function tryScoop(state, id, pl, tick) {
  var held = handItem(state, id, "bucket");
  if (!held) return false;
  var comp = compartmentAt(pl.z);
  if (state.water.comps[comp].w <= 0) return false;
  var last = state.bilge.scoopTick[id];
  if (last !== undefined && tick - last < BUCKET_COOLDOWN_TICKS) return true;
  waterRemove(state.water, comp, BUCKET_VOLUME);
  state.bilge.scoopTick[id] = tick;
  return true;
}

// Broadcast (and resync): s = 0 stopped, 1 on, 2 broken; r = 1 when the pump is actually moving water this tick.
function bilgeView(b) {
  var out = [];
  for (var i = 0; i < b.pumps.length; i++) out.push({ s: b.pumps[i].broken ? 2 : (b.pumps[i].on ? 1 : 0), r: b.pumps[i].run ? 1 : 0 });
  return out;
}

// ---- Electrical network: bus voltage, breakers, emergency battery (E3-07) ------------------------------------------------------
// The turbine makes E (MWe). The reactor's primary pumps are on the ESSENTIAL bus and take their share first (reactor.js, untouched). What is
// left, SURPLUS = max(0, E - essential demand), feeds the boat's consumers through 20 breakers. The bus VOLTAGE V (0..1) follows
// supply / demand slowly: it rises with TAU_UP, it declines slowly with TAU_DOWN ("l'air et la lumière déclinent lentement" in Veille, GDD 3.3),
// but a SCRAM cuts it at once ("tue instantanément toute l'électricité"). The lights show V as white -> orange -> red -> black, the
// signature of the game. A small BATTERY feeds an emergency bus (red emergency lights) while the grid is dark: it charges when V is high,
// lasts ~10 minutes. Breakers can be opened by players (shedding load), TRIP by themselves when the voltage stays low although power exists
// (the biggest closed consumer goes first), and are re-armed by hand at the panel. Effects: lights per compartment and the bilge pumps
// today; the other consumers only report whether they are powered (their gameplay comes with their epics: air E6-06, sonar/radio, ...).
var TAU_UP = 30;                 // s: voltage rise
var TAU_DOWN = 120;              // s: slow decline when supply falls short (a SCRAM is instantaneous)
var TRIP_V = 0.4;                // a breaker trips when V stays below this ...
var TRIP_TICKS = 50;             // ... for 5 s while the plant still produces surplus (nothing to shed otherwise)
var SETTLED = 0.02;               // the voltage counts as settled when the target is at most this far above it
var DARK_V = 0.2;                // below this the grid counts as dark: the emergency bus takes over
var BATTERY_DRAIN_S = 600;       // s of emergency light on a full battery
var BATTERY_CHARGE_S = 900;      // s to charge it from empty while the voltage is high
var BATTERY_CHARGE_V = 0.9;
var BILGE_MIN_V = 0.5;           // the bilge pumps need this voltage (and their breaker closed)

// 20 breakers, one consumer each. Spike layout: floor tiles 0.5 m apart (3 columns x 7 rows) at the stern, left wall, because the spike's
// interaction works on position, not on aim (E2-02 will replace this by a real panel: the positions are data).
var BREAKERS = [
  { id: "light1", demand: 0.15, use: "light", comp: 0 }, { id: "light2", demand: 0.15, use: "light", comp: 1 },
  { id: "light3", demand: 0.15, use: "light", comp: 2 }, { id: "light4", demand: 0.15, use: "light", comp: 3 },
  { id: "light5", demand: 0.15, use: "light", comp: 4 }, { id: "light6", demand: 0.15, use: "light", comp: 5 },
  { id: "bilge0", demand: 0.4, use: "bilge", pump: 0 }, { id: "bilge1", demand: 0.4, use: "bilge", pump: 1 },
  { id: "sonar", demand: 0.6 }, { id: "radio", demand: 0.3 }, { id: "cipher", demand: 0.15 }, { id: "ventilation", demand: 0.5 },
  { id: "galley", demand: 0.5 }, { id: "samovar", demand: 0.25 }, { id: "coffee", demand: 0.25 }, { id: "shower", demand: 0.3 },
  { id: "periscope", demand: 0.15 }, { id: "interphone", demand: 0.15 }, { id: "heater", demand: 0.4 }, { id: "pneumatic", demand: 0.1 }
];
(function placeBreakers() {
  for (var i = 0; i < BREAKERS.length; i++) {
    BREAKERS[i].x = -2.5 + 0.5 * (i % 3);
    BREAKERS[i].z = -9.75 + 0.5 * Math.floor(i / 3);
    BREAKERS[i].reach = 0.3;
  }
})();

function newPower() {
  var br = [];
  for (var i = 0; i < BREAKERS.length; i++) br.push({ closed: true, tripped: false });
  return { V: 1, B: 1, br: br, lowTicks: 0 };
}

// Power drawn by the closed breakers (MWe), the whole demand (breakers + propulsion, E3-08) and the surplus the plant offers them.
function powerDemand(state) { return gridDemand(state.power) + propulsionDemand(state.prop); }
function gridDemand(pw) {
  var d = 0;
  for (var i = 0; i < BREAKERS.length; i++) if (pw.br[i].closed) d += BREAKERS[i].demand;
  return d;
}
function gridSurplus(reactor) {
  var essential = ((reactor.pumps[0] ? 1 : 0) + (reactor.pumps[1] ? 1 : 0)) * REACTOR_K.pumpDemand;
  return Math.max(0, reactor.E - essential);
}

// A press at a breaker: closed -> open (shedding a load); open or tripped -> closed (re-arm). The next step decides if it holds.
function breakerToggle(pw, i) {
  var b = pw.br[i];
  if (b.closed) { b.closed = false; b.tripped = false; } else { b.closed = true; b.tripped = false; }
  return true;
}
function breakerTrip(pw, i) { pw.br[i].closed = false; pw.br[i].tripped = true; return true; }

// Is a consumer fed? (its breaker is closed and the bus voltage is at least minV)
function consumerPowered(pw, i, minV) { return pw.br[i].closed && pw.V >= minV; }

// One 10 Hz step, after the reactor.
function powerStep(state) {
  var pw = state.power, r = state.reactor;
  var demand = powerDemand(state), surplus = gridSurplus(r);
  var target = demand > 0 ? Math.min(1, surplus / demand) : 1;
  if (r.scram) {
    pw.V = 0;                                              // the SCRAM tears the whole grid down at once
  } else {
    pw.V += (target - pw.V) * DT / (target > pw.V ? TAU_UP : TAU_DOWN);
  }
  // emergency battery: carries the emergency bus while the grid is dark, charges while the voltage is high
  if (pw.V < DARK_V) pw.B = Math.max(0, pw.B - DT / BATTERY_DRAIN_S);
  else if (pw.V > BATTERY_CHARGE_V) pw.B = Math.min(1, pw.B + DT / BATTERY_CHARGE_S);
  // load shedding: the voltage is low and NOT recovering (it has settled within SETTLED of the target supply ratio, or is above it: a structural
  // overload, not the plant spinning up after a restart) although the plant produces surplus -> the biggest closed consumer trips
  if (!r.scram && surplus > 0 && pw.V < TRIP_V && target <= pw.V + SETTLED) {
    pw.lowTicks++;
    if (pw.lowTicks >= TRIP_TICKS) {
      var big = -1;
      for (var i = 0; i < BREAKERS.length; i++) if (pw.br[i].closed && (big < 0 || BREAKERS[i].demand > BREAKERS[big].demand)) big = i;
      if (big >= 0) breakerTrip(pw, big);
      pw.lowTicks = 0;
    }
  } else pw.lowTicks = 0;
}

// Light level of a compartment: the bus voltage when its lights breaker is closed. Band: 3 white, 2 orange, 1 red, 0 dark.
function lightLevel(pw, comp) {
  for (var i = 0; i < BREAKERS.length; i++) if (BREAKERS[i].use === "light" && BREAKERS[i].comp === comp) return pw.br[i].closed ? pw.V : 0;
  return 0;
}
function lightBand(level) { return level >= 0.8 ? 3 : (level >= 0.5 ? 2 : (level >= DARK_V ? 1 : 0)); }

// Broadcast (and resync): v = bus voltage, b = battery 0..1, em = emergency lights on (grid dark, battery left), br = per breaker 0 open / 1 closed /
// 2 tripped, lt = light band per compartment (3 white .. 0 dark), dm = demand, su = surplus (MWe).
function powerView(state) {
  var pw = state.power, br = [], lt = [];
  function q(x, k) { return Math.round(x * k) / k; }
  for (var i = 0; i < BREAKERS.length; i++) br.push(pw.br[i].tripped ? 2 : (pw.br[i].closed ? 1 : 0));
  for (var c = 0; c < WATER_COMPARTMENTS.length; c++) lt.push(lightBand(lightLevel(pw, c)));
  return { v: q(pw.V, 1000), b: q(pw.B, 1000), em: pw.V < DARK_V && pw.B > 0 ? 1 : 0, br: br, lt: lt, dm: q(powerDemand(state), 100), su: q(gridSurplus(state.reactor), 100) };
}

// ---- Propulsion and the machine telegraph (E3-08) ------------------------------------------------------------------------------
// GDD 3.3: turbine -> electricity + propulsion. Decision (E3-08): propulsion is a CONSUMER of the electrical network (power.js), not a share of
// the steam, so the reactor's balance (E3-02) is untouched: the telegraph position adds its demand to the grid's, which lowers the bus voltage
// unless the plant makes enough surplus. "The faster we go, the darker it gets", and full speed needs full power. The boat's speed follows the
// telegraph set-point scaled by the bus voltage, with inertia: after a SCRAM the boat coasts and slows down. Position (distance) is accumulated
// for the future map (E9). The total noise of the boat (E8-01) will add PROPULSION noise to the reactor's; here it is only a derived value.
//
// Telegraph: 5 positions of a brass dial. Spike interaction: two floor tiles, "up" and "down", one notch per press (the aimed handle is E2-02).
var PROP_NAMES = ["arriere", "stop", "lent", "demi", "toute"];
var PROP_DEMAND = [1.0, 0, 1.0, 2.5, 5.0];                 // MWe added to the grid demand
var PROP_SPEED = [-0.3, 0, 0.3, 0.6, 1.0];                 // set-point as a fraction of PROP_VMAX
var PROP_VMAX = 6;                                         // m/s (about 12 knots)
var PROP_TAU = 15;                                         // s: inertia of the boat's speed
var PROP_STOP = 1;                                         // index of "stop", the starting position

function newPropulsion() { return { pos: PROP_STOP, speed: 0, dist: 0 }; }

// One notch up (+1) or down (-1) on the telegraph, stopping at the ends. Returns whether the handle moved.
function telegraphStep(prop, dir) {
  var next = Math.max(0, Math.min(PROP_NAMES.length - 1, prop.pos + (dir > 0 ? 1 : -1)));
  if (next === prop.pos) return false;
  prop.pos = next;
  return true;
}

function propulsionDemand(prop) { return PROP_DEMAND[prop.pos]; }

// One 10 Hz step, after the electrical network: the speed eases towards set-point x bus voltage.
function propulsionStep(state) {
  var p = state.prop, V = state.power.V;
  var target = PROP_SPEED[p.pos] * PROP_VMAX * V;
  p.speed += (target - p.speed) * DT / PROP_TAU;
  p.dist += p.speed * DT;
}

// Propulsion noise 0..4, from the speed (the telegraph alone makes none: a stopped boat is quiet).
function propulsionNoise(prop) { return 4 * Math.min(1, Math.abs(prop.speed) / PROP_VMAX); }

// Broadcast (and resync): p = telegraph position 0..4, s = speed m/s, d = distance travelled m, n = noise 0..4.
function propulsionView(prop) {
  function q(x, k) { return Math.round(x * k) / k; }
  return { p: prop.pos, s: q(prop.speed, 100), d: q(prop.dist, 10), n: q(propulsionNoise(prop), 100) };
}

// ---- Reactor RK-1 "Petit Soleil" (E3-02) -------------------------------------------------------------------
// Authoritative, deterministic model (fixed step = 1 tick = 0.1 s, seeded PRNG, no wall-clock). Design and
// constants: docs/design/reactor-dependency-tree.md. All constants are starting hypotheses to be tuned by playtests.
//
// Chain:  regime -> rods R -> fission power Pf -> (+ decay heat) -> heat P -> core temperature T
//         T -> steam pressure S -> turbine electricity E -> essential bus (primary pumps) -> cooling flow F -> T
// The cooling loop is fed by the electricity the reactor itself produces ("boucle diabolique"). The SCRAM drops
// every control rod and kills all electricity at once; only natural circulation is left.

var REACTOR_K = {
  rodRate: 0.02,           // rods travel per second (SCRAM: x20)
  scramRodFactor: 20,
  regimes: { veille: 0.10, croisiere: 0.45, pleine: 0.90 },
  pMax: 100,               // MWth with rods fully out
  tauP: 10,                // s, fission power lag
  decayFrac: 0.07,         // decay heat = 7 % of the smoothed power
  tauDecay: 180,           // s
  coreC: 160,              // MJ per degC (core thermal inertia)
  kCool: 1.3,              // MW per degC per unit of coolant flow
  tIn: 280,                // degC, coolant inlet
  flowPump: 0.5,           // flow per primary pump at full electric supply
  flowNat: 0.15,           // natural circulation (always there, only source after a SCRAM)
  tauS: 40,                // s, steam pressure lag
  barPerDeg: 100 / 30,     // steam pressure target per degC above the inlet
  tauE: 70,                // s, turbine/electrical lag
  eCoef: 0.13,             // MWe per bar of steam pressure
  pumpDemand: 4,           // MWe per running primary pump (essential bus)
  tWarn: 350,              // degC, alert threshold
  tCrit: 370,              // degC, critical threshold
  critHoldSeconds: 30,     // at T >= tCrit for this long: automatic protection (SCRAM + primary leak)
  firstDriftSeconds: 30,
  driftMeanSeconds: 5.0,   // mean delay between coolant-valve drifts at R = 1 (scales as 1 / R^2)
  driftMin: 0.05, driftMax: 0.15,
  settleSeconds: 900       // initial steady-state run (drift disabled)
};

// Seeded PRNG (mulberry32): the state is a single uint32 stored in the reactor, so runs are reproducible.
function reactorRand(r) {
  r.rng = (r.rng + 0x6D2B79F5) | 0;
  var t = Math.imul(r.rng ^ (r.rng >>> 15), 1 | r.rng);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
}

function newReactor(seed, regime) {
  regime = regime || "veille";
  var K = REACTOR_K;
  var R = K.regimes[regime];
  var r = {
    t: 0, seed: seed, rng: seed | 0, regime: regime,
    R: R, Pf: K.pMax * R, A: K.pMax * R, T: K.tIn + 20, S: 30, E: 0,
    valves: [1, 1, 1, 1], pumps: [true, true], pumpBroken: [false, false],
    scram: false, autoScram: false, leak: false, critTimer: 0,
    nextDrift: K.firstDriftSeconds, driftEnabled: false,
    eta: 0, flow: 0, P: 0
  };
  for (var i = 0; i < K.settleSeconds / DT; i++) reactorStep(r);   // reach the steady state of the chosen regime
  r.t = 0; r.driftEnabled = true; r.nextDrift = K.firstDriftSeconds;
  return r;
}

function reactorSetRegime(r, regime) {
  if (!REACTOR_K.regimes.hasOwnProperty(regime)) return false;
  r.regime = regime;
  return true;
}

function reactorSetValve(r, index, position) {
  if (index < 0 || index > 3) return false;
  r.valves[index] = clamp(position, 0, 1);
  return true;
}

// A broken pump (E3-06) cannot be started; stopping one is always possible.
function reactorSetPump(r, index, on) {
  if (index < 0 || index > 1) return false;
  if (on && r.pumpBroken[index]) return false;
  r.pumps[index] = !!on;
  return true;
}

// Breakdown / repair of a primary pump. Nothing triggers a breakdown yet (the failure generator is E3-09) and the spare part that
// repairs one is E5/E9; a repaired pump stays stopped until a player starts it.
function reactorBreakPump(r, index) {
  if (index < 0 || index > 1) return false;
  r.pumpBroken[index] = true; r.pumps[index] = false;
  return true;
}
function reactorRepairPump(r, index) {
  if (index < 0 || index > 1) return false;
  r.pumpBroken[index] = false;
  return true;
}

// SCRAM: any player, any time, no vote. All electricity is lost immediately.
function reactorScram(r) {
  r.scram = true;
  r.E = 0;
}

// Clears the SCRAM latch. The two-player procedure that guards it is E3-05; this is only the model side.
function reactorRestart(r) {
  r.scram = false; r.autoScram = false; r.critTimer = 0;
}

function reactorStep(r) {
  var K = REACTOR_K;
  var dt = DT;
  // 1. Rods follow the regime set-point (or drop on SCRAM)
  var target = r.scram ? 0 : K.regimes[r.regime];
  var rate = K.rodRate * dt * (r.scram ? K.scramRodFactor : 1);
  r.R += clamp(target - r.R, -rate, rate);
  // 2. Heat
  r.Pf += (K.pMax * r.R - r.Pf) * dt / K.tauP;
  r.A += (r.Pf - r.A) * dt / K.tauDecay;
  r.P = r.Pf + K.decayFrac * r.A;
  // 3. Electricity: the turbine is driven by steam only; pumps are on the essential bus (first priority)
  var pumpsOn = (r.pumps[0] ? 1 : 0) + (r.pumps[1] ? 1 : 0);
  var essential = pumpsOn * K.pumpDemand;
  var eTarget = r.scram ? 0 : K.eCoef * r.S;
  r.E += (eTarget - r.E) * dt / K.tauE;
  r.eta = essential > 0 ? Math.min(1, r.E / essential) : 0;
  // 4. Cooling flow and core temperature
  var valveFactor = (r.valves[0] + r.valves[1] + r.valves[2] + r.valves[3]) / 4;
  r.flow = pumpsOn * K.flowPump * r.eta * valveFactor + K.flowNat;
  r.T += (r.P - K.kCool * r.flow * (r.T - K.tIn)) / K.coreC * dt;
  // 5. Steam pressure follows the core temperature
  var sTarget = Math.max(0, (r.T - K.tIn) * K.barPerDeg);
  r.S += (sTarget - r.S) * dt / K.tauS;
  // 6. Random drift of the cooling valves ("active monitoring"): faster at higher rod position
  if (r.driftEnabled && !r.scram) {
    r.nextDrift -= dt;
    if (r.nextDrift <= 0) {
      var i = Math.floor(reactorRand(r) * 4);
      r.valves[i] = Math.max(0, r.valves[i] - (K.driftMin + reactorRand(r) * (K.driftMax - K.driftMin)));
      r.nextDrift = K.driftMeanSeconds / Math.max(0.01, r.R * r.R) * (0.5 + reactorRand(r));
    }
  }
  // 7. Automatic protection: critical temperature held too long -> SCRAM and a primary-circuit leak (never an explosion)
  if (r.driftEnabled && r.T >= K.tCrit) {
    r.critTimer += dt;
    if (!r.autoScram && r.critTimer >= K.critHoldSeconds) { r.autoScram = true; r.leak = true; reactorScram(r); }
  } else if (r.driftEnabled) {
    r.critTimer = 0;
  }
  r.t += dt;
}

// Noise made by the plant, 0 (quiet, Veille) to 4 (loud, Pleine puissance): follows the REAL rod position, so it lags the
// regime selector like everything else. The boat's total noise (E8-01) will add pumps, impacts and voices on top.
function reactorNoise(r) {
  var lo = REACTOR_K.regimes.veille, hi = REACTOR_K.regimes.pleine;
  return 4 * clamp((r.R - lo) / (hi - lo), 0, 1);
}

// Gauge values broadcast to clients (rounded: keeps the payload small and the display stable).
function reactorView(r) {
  function q(x) { return Math.round(x * 100) / 100; }
  return {
    reg: r.regime, R: q(r.R), nz: q(reactorNoise(r)), P: q(r.P), T: q(r.T), S: q(r.S), E: q(r.E), eta: q(r.eta), F: q(r.flow),
    v: [q(r.valves[0]), q(r.valves[1]), q(r.valves[2]), q(r.valves[3])],
    pu: [r.pumpBroken[0] ? 2 : (r.pumps[0] ? 1 : 0), r.pumpBroken[1] ? 2 : (r.pumps[1] ? 1 : 0)],   // 0 stopped, 1 running, 2 broken
    scram: r.scram ? 1 : 0, auto: r.autoScram ? 1 : 0, leak: r.leak ? 1 : 0,
    warn: r.T >= REACTOR_K.tWarn ? 1 : 0, crit: r.T >= REACTOR_K.tCrit ? 1 : 0
  };
}

// ---- Boat buoyancy (E3-04) ----------------------------------------------------------------------------------
// After a SCRAM the boat has no electricity: ballast pumps and trim stop and it starts to sink, slowly (GDD 3.3: "sous-marin qui
// commence à couler doucement"). The descent speed ramps up to SINK_RATE_MAX over SINK_RAMP_SECONDS and eases back to zero when the
// reactor is restarted (E3-05). The boat does not rise by itself and nothing here destroys it: crush depth, flooding and damage are
// other epics (E6/E7). Deterministic: a function of the tick count and the reactor's SCRAM latch only.
var SINK_RATE_MAX = 0.2;       // m/s at full descent
var SINK_RAMP_SECONDS = 20;    // time to go from 0 to SINK_RATE_MAX (and back)

function newBoat() {
  return { depth: 0, vz: 0 };   // depth below the patrol depth (m, grows when sinking); vz = descent speed (m/s)
}

function boatStep(boat, reactor) {
  var dv = SINK_RATE_MAX / (SINK_RAMP_SECONDS * TICK_RATE);
  if (reactor.scram) boat.vz = Math.min(SINK_RATE_MAX, boat.vz + dv);
  else boat.vz = Math.max(0, boat.vz - dv);
  boat.depth += boat.vz * DT;
}

function boatView(boat) {
  return { d: Math.round(boat.depth * 100) / 100, vz: Math.round(boat.vz * 1000) / 1000 };
}

// ---- Interactive controls (boat-local) ---------------------------------------------------------------------
// One interaction key ("act") serves every control: the server picks the nearest interactable within reach, so the
// client never has to say what it is pressing (and cannot cheat about it). Coupled-action commands live in coupled.js;
// the other controls are listed here.
//   regime : the RK-1 three-position selector (compartment 4, left wall). One press turns it to the next position
//            (Veille -> Croisiere -> Pleine -> Veille). A single player is enough: the Rule of Two Players covers
//            starting/stopping the reactor, not choosing a regime (GDD 3.3/3.4).
//   scram  : the SCRAM lever under its sealed cover (E3-04), 1 m from the selector. Two presses, one player, no vote: the first lifts
//            the cover (it falls shut again after LEVER_COVER_TICKS), the second, cover open, pulls the lever. This is the one critical
//            action that is deliberately NOT under the Rule of Two Players (GDD 3.3). Pulling it again does nothing; restarting is E3-05.
//   valve0..3 : the four primary-circuit valve handwheels (E3-06), right wall. HOLD the interaction key to turn one open (VALVE_TURN_RATE per
//            second); drift closes them, only players open them. One player is enough.
//   pump0..1  : the two primary pumps' switches (E3-06). One press toggles run/stop; a broken pump cannot be started (repair is E5/E9).
var CONTROLS = [
  { id: "regime", x: -2.5, z: -1.7, reach: 2.0 },
  { id: "scram", x: -2.5, z: -2.7, reach: 1.5 },
  { id: "valve0", x: 2.5, z: -3.0, reach: 1.0, valve: 0 },
  { id: "valve1", x: 2.5, z: -1.5, reach: 1.0, valve: 1 },
  { id: "valve2", x: 2.5, z: 0.0, reach: 1.0, valve: 2 },
  { id: "valve3", x: 2.5, z: 1.5, reach: 1.0, valve: 3 },
  { id: "pump0", x: 2.5, z: 3.5, reach: 1.2, pump: 0 },
  { id: "pump1", x: 2.5, z: 5.0, reach: 1.2, pump: 1 },
  { id: "bilge0", x: -2.5, z: 4.5, reach: 1.0, bilge: 0 },
  { id: "bilge1", x: 2.5, z: -5.0, reach: 0.9, bilge: 1 }
];
var VALVE_TURN_RATE = 0.25;        // valve opening per second while the wheel is held (4 s from closed to open)
(function addBreakerControls() {                        // the 20 breakers of the main panel (E3-07): floor tiles at the stern, left wall
  for (var i = 0; i < BREAKERS.length; i++)
    CONTROLS.push({ id: "breaker_" + BREAKERS[i].id, x: BREAKERS[i].x, z: BREAKERS[i].z, reach: BREAKERS[i].reach, breaker: i });
})();
CONTROLS.push({ id: "tele_up", x: -0.5, z: 4.2, reach: 0.3, tele: 1 }, { id: "tele_down", x: -0.5, z: 3.6, reach: 0.3, tele: -1 });   // machine telegraph (E3-08)
var LEVER_COVER_TICKS = 60;        // 6 s at 10 Hz
var REGIME_ORDER = ["veille", "croisiere", "pleine"];

function controlDistance(pl, c) {
  var dx = pl.x - c.x, dz = pl.z - c.z;
  return Math.sqrt(dx * dx + dz * dz);
}

// Turn the selector one position. Ignored while the reactor is SCRAMmed (restarting is the E3-05 procedure).
function useRegimeSelector(reactor) {
  if (reactor.scram) return false;
  var next = REGIME_ORDER[(REGIME_ORDER.indexOf(reactor.regime) + 1) % REGIME_ORDER.length];
  return reactorSetRegime(reactor, next);
}

// Hold the interaction key near a valve wheel: it turns open by VALVE_TURN_RATE * DT per applied input (one input per tick).
function holdValve(reactor, index) {
  return reactorSetValve(reactor, index, reactor.valves[index] + VALVE_TURN_RATE * DT);
}

function togglePump(reactor, index) {
  return reactorSetPump(reactor, index, !reactor.pumps[index]);
}

// The nearest control within its reach (or null).
function nearestControl(pl) {
  var best = null, bestD = Infinity;
  for (var i = 0; i < CONTROLS.length; i++) {
    var d = controlDistance(pl, CONTROLS[i]);
    if (d <= CONTROLS[i].reach && d < bestD) { best = CONTROLS[i]; bestD = d; }
  }
  return best;
}

// The interaction key is HELD (input flag `hold`, sent every tick while the key is down): only valve wheels use it.
function tryHold(state, pl) {
  if (!canUseHands(pl)) return;                        // E2-03: a hand must be free
  var c = nearestControl(pl);
  if (c && c.valve !== undefined) holdValve(state.reactor, c.valve);
}

// cover = ticks left before the cover falls shut (0 = closed); reset = the lever was put back after a SCRAM (restart step 1, E3-05)
function newLever() { return { cover: 0, reset: false }; }

// First press lifts the cover, second press (cover open) pulls the lever. Returns true when the SCRAM was triggered.
function useScramLever(lever, reactor) {
  if (reactor.scram) { lever.reset = true; return false; }   // a press on a pulled lever puts it back (restart step 1); the latch stays until the restart
  if (lever.cover <= 0) { lever.cover = LEVER_COVER_TICKS; return false; }
  reactorScram(reactor);
  lever.cover = 0;
  return true;
}

function leverStep(lever) { if (lever.cover > 0) lever.cover--; }

// Broadcast: cv = cover open (stays open while the lever is down), pl = lever pulled (the reactor latch, so a restart resets both).
function leverView(lever, reactor) {
  return { cv: (lever.cover > 0 || reactor.scram) ? 1 : 0, pl: reactor.scram ? 1 : 0 };
}

// Press a control (the effect of one press, whoever chose it: the nearest-in-reach path or the aimed one).
function activateControl(state, c) {
  if (c.id === "regime") useRegimeSelector(state.reactor);
  else if (c.id === "scram") useScramLever(state.lever, state.reactor);
  else if (c.pump !== undefined) togglePump(state.reactor, c.pump);
  else if (c.bilge !== undefined) bilgeToggle(state.bilge, c.bilge);
  else if (c.breaker !== undefined) breakerToggle(state.power, c.breaker);
  else if (c.tele !== undefined) telegraphStep(state.prop, c.tele);
}

// The interaction key was pressed by player `id`: dispatch to the nearest interactable in reach (the position-based path: bots, tests, the
// key E). The aimed path is useTarget.
function tryAct(state, id, pl, tick) {
  if (tryRepair(state, id, pl, tick)) return;           // carrying a hull patch next to a leak: the press applies it (E6-02)
  if (tryScoop(state, id, pl, tick)) return;            // carrying the bucket in a flooded compartment: the press scoops (E6-03)
  var bestControl = null, bestControlD = Infinity;
  for (var i = 0; i < CONTROLS.length; i++) {
    var d = controlDistance(pl, CONTROLS[i]);
    if (d <= CONTROLS[i].reach && d < bestControlD) { bestControl = CONTROLS[i]; bestControlD = d; }
  }
  var cmd = nearestCommand(pl);
  var bestStationD = cmd ? cmd.d : Infinity;
  if (!canUseHands(pl)) return;                         // E2-03: pressing a control needs a free hand and no two-handed item
  if (bestControl && bestControlD < bestStationD) { activateControl(state, bestControl); return; }
  if (cmd) tryActivate(state.cp, id, pl, tick);
}

// ---- Aimed interaction (E2-02) ------------------------------------------------------------------------------------------------
// The client looks at an object and sends its id in the input field `use`; the server checks that the id exists and that the player is within
// arm's reach, then does what a press on that object does. Ids: a control id of CONTROLS ("regime", "scram", "valve0".."pump1", "bilge0",
// "breaker_<id>", "tele_up"...), "cc:<action>:<0|1>" for a command of the Rule of Two Players, "leak:<n>" for a hull leak, and "item" for
// "use what I hold" (a patch on a leak, the bucket in the water). Anything else, or out of reach, is ignored.
var AIM_REACH = 2.0;                 // m: arm's reach for every aimed control (the aim removes the ambiguity the small tiles had to solve by position)

function controlById(id) {
  for (var i = 0; i < CONTROLS.length; i++) if (CONTROLS[i].id === id) return CONTROLS[i];
  return null;
}

// Every id the server accepts, except the dynamic "leak:<n>": views and tests use it to stay in step with the server.
function interactableIds() {
  var ids = ["item"];
  for (var i = 0; i < CONTROLS.length; i++) ids.push(CONTROLS[i].id);
  for (var a = 0; a < COUPLED_ACTIONS.length; a++) { ids.push("cc:" + COUPLED_ACTIONS[a].id + ":0"); ids.push("cc:" + COUPLED_ACTIONS[a].id + ":1"); }
  return ids;
}

// A press (input flag act) on the object with id `target`.
function useTarget(state, id, pl, tick, target) {
  if (target === "item") { if (!tryRepair(state, id, pl, tick)) tryScoop(state, id, pl, tick); return; }
  if (target.indexOf("leak:") === 0) {
    var n = +target.slice(5);
    for (var l = 0; l < state.leaks.list.length; l++) if (state.leaks.list[l].id === n) { tryRepair(state, id, pl, tick, state.leaks.list[l]); return; }
    return;
  }
  if (!canUseHands(pl)) return;                         // E2-03: controls and commands need a free hand; the item uses above do not
  if (target.indexOf("cc:") === 0) {
    var parts = target.split(":");
    var side = +parts[2];
    if (parts.length !== 3 || (side !== 0 && side !== 1)) return;
    for (var a = 0; a < COUPLED_ACTIONS.length; a++) {
      if (COUPLED_ACTIONS[a].id !== parts[1]) continue;
      var cmd = side === 0 ? COUPLED_ACTIONS[a].a : COUPLED_ACTIONS[a].b;
      var dx = pl.x - cmd.x, dz = pl.z - cmd.z;
      if (Math.sqrt(dx * dx + dz * dz) <= Math.max(cmd.reach, AIM_REACH)) armCommand(state.cp, id, tick, a, side);
      return;
    }
    return;
  }
  var c = controlById(target);
  if (c && controlDistance(pl, c) <= AIM_REACH) activateControl(state, c);
}

// The key is HELD on the object with id `target`: only the valve wheels use it.
function holdTarget(state, pl, target) {
  if (!canUseHands(pl)) return;
  var c = controlById(target);
  if (c && c.valve !== undefined && controlDistance(pl, c) <= AIM_REACH) holdValve(state.reactor, c.valve);
}

// ---- Reactor restart procedure after a SCRAM (E3-05) ----------------------------------------------------------------
// GDD 3.3: restarting is a two-player procedure, by torchlight, following the manual. Three preparation steps anyone can do, in any
// order (so the two players can split them), then a coupled action (Rule of Two Players, E4-02) that actually restarts the plant:
//   1. lever    : put the SCRAM lever back (one press at the lever while the reactor is SCRAMmed)
//   2. valves   : the four primary valves open to at least RESTART_VALVE_MIN (the wheels are held open, E3-06)
//   3. pumps    : both primary pumps running (not stopped, not broken)
//   4. restart  : the coupled action "reactor_restart" (two commands far apart, two different players, 3 s window)
// Step 4 is refused until 1-3 are done (result "refused", no penalty). Batteries (E3-07) and the manual pages (E5) are not modelled yet.
var RESTART_VALVE_MIN = 0.9;

function newRestart() { return { last: "none", lastTick: 0, count: 0 }; }

function restartSteps(state) {
  var r = state.reactor, v = r.valves, ok = true;
  for (var i = 0; i < 4; i++) if (v[i] < RESTART_VALVE_MIN) ok = false;
  return [
    state.lever.reset === true,
    ok,
    r.pumps[0] === true && r.pumps[1] === true && !r.pumpBroken[0] && !r.pumpBroken[1]
  ];
}

// Effect of the coupled action "reactor_restart": succeeds only on a SCRAMmed reactor whose three preparation steps are done.
function restartAttempt(state, id, tick) {
  var steps = restartSteps(state);
  if (state.reactor.scram && steps[0] && steps[1] && steps[2]) {
    reactorRestart(state.reactor);
    state.lever.reset = false; state.lever.cover = 0;
    state.restart.last = "success"; state.restart.count++;
  } else {
    state.restart.last = "refused";
  }
  state.restart.lastTick = tick;
}
COUPLED_EFFECTS.reactor_restart = restartAttempt;

// Broadcast (and resync): s = the three preparation steps (1 done), last = outcome of the latest attempt, lt = its tick, n = restarts so far.
function restartView(state) {
  var s = restartSteps(state);
  return { s: [s[0] ? 1 : 0, s[1] ? 1 : 0, s[2] ? 1 : 0], last: state.restart.last, lt: state.restart.lastTick, n: state.restart.count };
}

// ---- The fixed-step simulation (E1-06) ------------------------------------------------------------------------------------
// The whole authoritative game state advances in ONE function, simStep(state, tick), called by the match loop exactly once per 10 Hz tick. It
// has no knowledge of Nakama, the network or the clock: it reads and writes `state` and nothing else, so it can be driven headlessly (tests,
// the balance tool of E3-10) and gives the same result for the same inputs. Rules that keep it deterministic (CLAUDE.md, architecture rule 1):
//   - no wall-clock time (Date, performance.now), no timers, no Math.random: randomness only from a seeded generator stored IN the state
//     (reactor drift, leak schedule); a test scans server/src for the forbidden APIs;
//   - iteration order is fixed (arrays and the players' join order, never object key order).
//
// Order of the steps inside a tick (changing it changes the game: the golden digest test will tell):
//   1. inputs      queued player inputs applied under the per-player budget (movement, press / hold / grab)
//   2. coupled     Rule of Two Players: arm / succeed / expire the coupled actions (and run their effects)
//   3. leaks       the scheduled leak may open; every open leak pours into its compartment
//   4. bilge       running bilge pumps take water out of their compartment
//   5. water       flow between compartments through the open openings (trim / list follow)
//   6. cargo       carried cargo follows its carriers, loose cargo slides on the (water-tilted) floor, used patches respawn; hands re-synced
//   7. reactor     rods, heat, steam, electricity, cooling, drift, automatic protection
//   8. power       bus voltage from the surplus electricity, emergency battery, breakers that trip
//   9. propulsion  the boat's speed follows the telegraph set-point x bus voltage
//  10. lever       the SCRAM cover falls shut
//  11. boat        buoyancy: descent speed and depth follow the SCRAM latch
function simStep(state, tick) {
  // 1. inputs: +1 per tick per player (the nominal input rate), capped at MAX_ALLOWANCE. In steady state this is exactly one input per tick;
  //    after a network stall (TCP retransmission) the backlog drains in a few ticks instead of lagging forever. The long-term rate can never
  //    exceed TICK_RATE inputs/s, so flooding the server with inputs does not speed a player up.
  for (var k = 0; k < state.order.length; k++) {
    var pl = state.players[state.order[k]];
    pl.allowance = Math.min(MAX_ALLOWANCE, pl.allowance + 1);
    while (pl.allowance >= 1 && pl.queue.length > 0) {
      var next = pl.queue.shift();
      if (next.ry !== null) pl.yaw = next.ry;
      stepPlayer(pl, next.mx, next.mz, carrySpeedFactor(state, state.order[k]));
      if (next.act) { if (next.use) useTarget(state, state.order[k], pl, tick, next.use); else tryAct(state, state.order[k], pl, tick); }
      if (next.hold) { if (next.use) holdTarget(state, pl, next.use); else tryHold(state, pl); }
      if (next.throw) throwItem(state, state.order[k], pl);
      if (next.take) takeItem(state, state.order[k], pl, tick);
      if (next.drop) dropItem(state, state.order[k], pl, next.drop);
      if (next.stow) stowItem(state, state.order[k], pl);
      if (next.grab) grabToggle(state, state.order[k], pl, tick);
      pl.seq = next.seq;
      pl.applied += 1;
      pl.allowance -= 1;
    }
  }
  evaluateCoupled(state, tick);
  leakStep(state, tick);
  bilgeStep(state);
  waterStep(state.water);
  updateCargo(state, tick);
  syncHands(state);
  reactorStep(state.reactor);
  powerStep(state);
  propulsionStep(state);
  leverStep(state.lever);
  boatStep(state.boat, state.reactor);
  state.tick = tick;
}

// Queue one parsed client input on a player (stale or duplicate sequences are rejected, a flooding client loses its oldest inputs).
function queueInput(p, input) {
  if (typeof input.seq !== "number" || input.seq <= p.lastQueued) return false;
  p.lastQueued = input.seq;
  p.queue.push({ seq: input.seq, mx: +input.mx || 0, mz: +input.mz || 0, act: input.act === true || input.act === 1,
                 grab: input.grab === true || input.grab === 1, hold: input.hold === true || input.hold === 1,
                 ry: typeof input.ry === "number" && isFinite(input.ry) ? input.ry : null,
                 throw: input.throw === true || input.throw === 1 || input.hand === "throw",
                 use: typeof input.use === "string" && input.use.length <= 40 ? input.use : "",
                 take: input.take === true || input.take === 1 || input.hand === "take", stow: input.stow === true || input.stow === 1 || input.hand === "stow",
                 drop: input.drop === "L" || input.drop === "R" || input.drop === "P" ? input.drop
                   : ((input.drop === true || input.drop === 1 || input.hand === "drop") ? "last"
                   : (typeof input.hand === "string" && input.hand.length === 6 && input.hand.indexOf("drop:") === 0 && "LRP".indexOf(input.hand.charAt(5)) >= 0 ? input.hand.charAt(5) : "")) });
  while (p.queue.length > MAX_QUEUED_INPUTS) p.queue.shift();
  return true;
}

// A 64-bit fingerprint (two FNV-1a hashes, hex) of the WHOLE game state: same state, same digest. Object keys are sorted so the digest does not
// depend on insertion order; the Nakama presence objects (network handles, not game state) are left out.
function stateDigest(state) {
  var text = stableStringify(state);
  var h1 = 0x811c9dc5, h2 = 0x01000193 ^ 0x9747b28c;
  for (var i = 0; i < text.length; i++) {
    var c = text.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 0x01000193) >>> 0;
    h2 = Math.imul(h2 ^ c, 0x85ebca6b) >>> 0;
  }
  return ("00000000" + h1.toString(16)).slice(-8) + ("00000000" + h2.toString(16)).slice(-8);
}

function stableStringify(v) {
  if (v === null || typeof v !== "object") return typeof v === "number" && !isFinite(v) ? "\"" + String(v) + "\"" : JSON.stringify(v);
  if (Array.isArray(v)) {
    var a = [];
    for (var i = 0; i < v.length; i++) a.push(stableStringify(v[i]));
    return "[" + a.join(",") + "]";
  }
  var keys = Object.keys(v).sort(), o = [];
  for (var k = 0; k < keys.length; k++) {
    if (keys[k] === "presence") continue;
    o.push(JSON.stringify(keys[k]) + ":" + stableStringify(v[keys[k]]));
  }
  return "{" + o.join(",") + "}";
}

var matchInit = function (ctx, logger, nk, params) {
  logger.info("moving_frame match init");
  return {
    state: { tick: 0, players: {}, order: [], cp: newCoupled(), cargo: newCargo(), reactor: newReactor(REACTOR_SEED, "veille"), lever: newLever(), boat: newBoat(), restart: newRestart(), water: newWater(), leaks: newLeaks(), bilge: newBilge(), power: newPower(), prop: newPropulsion() },
    tickRate: TICK_RATE,
    label: JSON.stringify({ name: MATCH_NAME })
  };
};

var matchJoinAttempt = function (ctx, logger, nk, dispatcher, tick, state, presence, metadata) {
  if (state.order.length >= MAX_PLAYERS && !state.players[presence.userId]) {
    return { state: state, accept: false, rejectMessage: "match full" };
  }
  return { state: state, accept: true };
};

var matchJoin = function (ctx, logger, nk, dispatcher, tick, state, presences) {
  for (var i = 0; i < presences.length; i++) {
    var id = presences[i].userId;
    if (!state.players[id]) {
      var slot = state.order.length;
      state.players[id] = { x: -1.5 + slot, z: 0, seq: 0, lastQueued: 0, allowance: 0, applied: 0, queue: [], hands: newHands(), yaw: 0, presence: presences[i] };
      state.order.push(id);
    }
  }
  return { state: state };
};

var matchLeave = function (ctx, logger, nk, dispatcher, tick, state, presences) {
  for (var i = 0; i < presences.length; i++) {
    var id = presences[i].userId;
    delete state.players[id];
    releaseCoupled(state.cp, id);
    releasePlayerItems(state, id);
    var idx = state.order.indexOf(id);
    if (idx >= 0) state.order.splice(idx, 1);
  }
  return { state: state };
};

var matchLoop = function (ctx, logger, nk, dispatcher, tick, state, messages) {
  // 1. Collect inputs (ordered by arrival). Drop the oldest if a client floods the queue.
  for (var i = 0; i < messages.length; i++) {
    var m = messages[i];
    if (m.opCode !== OP_INPUT) continue;
    var p = state.players[m.sender.userId];
    if (!p) continue;
    var input;
    try { input = JSON.parse(nk.binaryToString(m.data)); } catch (e) { continue; }
    queueInput(p, input);
  }

  // 2. Advance the whole simulation by one fixed step (server/src/sim.js: no Nakama, no clock, deterministic).
  simStep(state, tick);

  // 3. Broadcast authoritative state.
  var out = [];
  for (var j = 0; j < state.order.length; j++) {
    var id = state.order[j], q = state.players[id];
    out.push({ id: id, x: q.x, z: q.z, seq: q.seq, hd: handsView(q.hands) });
  }
  dispatcher.broadcastMessage(OP_STATE, JSON.stringify({ tick: tick, t: tick * DT, players: out, il: coupledView(state.cp, tick)[0], cp: coupledView(state.cp, tick), cargo: cargoView(state.cargo), rx: reactorView(state.reactor), sc: leverView(state.lever, state.reactor), rs: restartView(state), bw: waterView(state.water), lk: leaksView(state.leaks), bp: bilgeView(state.bilge), pw: powerView(state), pr: propulsionView(state.prop), boat: boatView(state.boat) }), null, null, true);
  return { state: state };
};

var matchTerminate = function (ctx, logger, nk, dispatcher, tick, state, graceSeconds) {
  return { state: state };
};

var matchSignal = function (ctx, logger, nk, dispatcher, tick, state, data) {
  return { state: state, data: data };
};

// The single moving-frame match id is published in storage at startup (match listing is indexed
// asynchronously, so it cannot be relied on right after creation). RPCs run in different JS VMs,
// hence storage instead of a module-level variable.
var SYSTEM_USER = "00000000-0000-0000-0000-000000000000";
var STORAGE = { collection: "system", key: "moving_frame_match" };

function publishMatch(nk) {
  var matchId = nk.matchCreate(MATCH_NAME, {});
  nk.storageWrite([{ collection: STORAGE.collection, key: STORAGE.key, userId: SYSTEM_USER,
                     value: { matchId: matchId }, permissionRead: 2, permissionWrite: 0 }]);
  return matchId;
}

// RPC: returns the id of the moving-frame match (creating it if none is published).
var rpcGetMatch = function (ctx, logger, nk, payload) {
  var objs = nk.storageRead([{ collection: STORAGE.collection, key: STORAGE.key, userId: SYSTEM_USER }]);
  var matchId = (objs && objs.length > 0) ? objs[0].value.matchId : publishMatch(nk);
  return JSON.stringify({ matchId: matchId });
};

function InitModule(ctx, logger, nk, initializer) {
  initializer.registerMatch(MATCH_NAME, {
    matchInit: matchInit,
    matchJoinAttempt: matchJoinAttempt,
    matchJoin: matchJoin,
    matchLeave: matchLeave,
    matchLoop: matchLoop,
    matchTerminate: matchTerminate,
    matchSignal: matchSignal
  });
  initializer.registerRpc("get_moving_frame_match", rpcGetMatch);
  publishMatch(nk); // fresh match (and fresh id) at every server start
  logger.info("moving_frame module loaded (tick rate %d Hz)", TICK_RATE);
}

// Allow tests in Node to import the handlers (ignored by the Nakama runtime).
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    InitModule: InitModule, stepPlayer: stepPlayer, simStep: simStep, queueInput: queueInput, stateDigest: stateDigest,
    TICK_RATE: TICK_RATE, DT: DT, STATIONS: STATIONS, STATION_REACH: STATION_REACH, INTERLOCK_WINDOW_TICKS: INTERLOCK_WINDOW_TICKS, MAX_ALLOWANCE: MAX_ALLOWANCE, MOVE_SPEED: MOVE_SPEED, HALF_X: HALF_X, HALF_Z: HALF_Z,
    OP_INPUT: OP_INPUT, OP_STATE: OP_STATE,
    LEVER_COVER_TICKS: LEVER_COVER_TICKS, SINK_RATE_MAX: SINK_RATE_MAX, SINK_RAMP_SECONDS: SINK_RAMP_SECONDS, newBoat: newBoat, boatStep: boatStep,
    VALVE_TURN_RATE: VALVE_TURN_RATE, reactorBreakPump: reactorBreakPump, reactorRepairPump: reactorRepairPump,
    RESTART_VALVE_MIN: RESTART_VALVE_MIN,
    BILGE_PUMPS: BILGE_PUMPS, BILGE_CAPACITY: BILGE_CAPACITY, BILGE_MIN_V: BILGE_MIN_V,
    PROP_NAMES: PROP_NAMES, PROP_DEMAND: PROP_DEMAND, PROP_SPEED: PROP_SPEED, PROP_VMAX: PROP_VMAX, PROP_TAU: PROP_TAU, newPropulsion: newPropulsion, telegraphStep: telegraphStep,
    propulsionStep: propulsionStep, propulsionNoise: propulsionNoise, powerDemand: powerDemand,
    BREAKERS: BREAKERS, TAU_UP: TAU_UP, TAU_DOWN: TAU_DOWN, TRIP_V: TRIP_V, TRIP_TICKS: TRIP_TICKS, DARK_V: DARK_V, BATTERY_DRAIN_S: BATTERY_DRAIN_S, BATTERY_CHARGE_S: BATTERY_CHARGE_S,
    newPower: newPower, powerStep: powerStep, powerView: powerView, breakerToggle: breakerToggle, breakerTrip: breakerTrip, gridDemand: gridDemand, gridSurplus: gridSurplus, lightLevel: lightLevel, lightBand: lightBand, BUCKET_VOLUME: BUCKET_VOLUME, BUCKET_COOLDOWN_TICKS: BUCKET_COOLDOWN_TICKS,
    bilgeBreak: bilgeBreak, bilgeRepair: bilgeRepair, bilgeToggle: bilgeToggle,
    LEAK_RATES: LEAK_RATES, LEAK_REACH: LEAK_REACH, LEAK_FIRST_TICK: LEAK_FIRST_TICK, PATCH_RESPAWN_TICKS: PATCH_RESPAWN_TICKS, leakCreate: leakCreate, leakRate: leakRate,
    WATER_COMPARTMENTS: WATER_COMPARTMENTS, WATER_FLOW: WATER_FLOW, MAX_TRIM_DEG: MAX_TRIM_DEG, MAX_LIST_DEG: MAX_LIST_DEG, newWater: newWater, waterAdd: waterAdd,
    waterRemove: waterRemove, waterSetDoor: waterSetDoor, waterStep: waterStep, waterTotal: waterTotal, waterTilt: waterTilt, waterView: waterView, waterLevel: waterLevel, compartmentAt: compartmentAt,
    newCoupled: newCoupled, COUPLED_ACTIONS: COUPLED_ACTIONS, COUPLED_EFFECTS: COUPLED_EFFECTS, COUPLED_GRACE_TICKS: COUPLED_GRACE_TICKS,
    carrySpeedFactor: carrySpeedFactor, carriedMass: carriedMass, throwItem: throwItem, THROW_SPEED: THROW_SPEED, THROW_UP: THROW_UP, THROW_HEIGHT: THROW_HEIGHT, THROW_BOUNCE: THROW_BOUNCE,
    ITEM_KINDS: ITEM_KINDS, newHands: newHands, takeItem: takeItem, dropItem: dropItem, stowItem: stowItem, canUseHands: canUseHands, handsView: handsView,
    AIM_REACH: AIM_REACH, interactableIds: interactableIds,
    CONTROLS: CONTROLS, REGIME_ORDER: REGIME_ORDER, tryAct: tryAct,
    reactorNoise: reactorNoise, REACTOR_K: REACTOR_K, newReactor: newReactor, reactorStep: reactorStep, reactorView: reactorView, reactorScram: reactorScram,
    reactorRestart: reactorRestart, reactorSetRegime: reactorSetRegime, reactorSetValve: reactorSetValve, reactorSetPump: reactorSetPump,
    GRAB_REACH: GRAB_REACH, GRAVITY: GRAVITY, FRICTION: FRICTION, boatUpHorizontal: boatUpHorizontal,
    handlers: { matchInit: matchInit, matchJoinAttempt: matchJoinAttempt, matchJoin: matchJoin, matchLeave: matchLeave, matchLoop: matchLoop }
  };
}
